const productosFalsos = [
    {
        product_id: 1,
        category_name: "Figuras colleccionables",
        licence_name: "Pokemon",
        product_name: "Charmander Smiley",
        product_description: "Figura coleccionable de Charmander, edición limitada",
        product_sku: "PKM001001",
        product_price: 12799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 35,
        img_front: "/img/pokemon/charmander-1.webp",
        img_back: "/img/pokemon/charmander-box.webp",
    },
    {
        product_id: 2,
        category_name: "Figuras colleccionables",
        licence_name: "Pokemon",
        product_name: "Pidgeotto",
        product_description: "Figura collecionable de Pidgeotto, edicion limitada",
        product_sku: "PKM001002",
        product_price: 3799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 25,
        img_front: "/img/pokemon/pidgeotto-1.webp",
        img_back: "/img/pokemon/pidgeotto-box.webp"
    },
    {
        product_id: 3,
        category_name: "Figuras colleccionables",
        licence_name: "Star Wars",
        product_name: "BabyYoda Blueball",
        product_description: "Figura colleccionable de BabyYoda, edicion limitada",
        product_sku: "STW001001",
        product_price: 4799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 15,
        img_front: "/img/star-wars/baby-yoda-1.webp",
        img_back: "/img/star-wars/baby-yoda-box.webp",
    },
    {
    product_id: 4,
        category_name: "Figuras colleccionables",
        licence_name: "Pokemon",
        product_name: "Charmander Smiley",
        product_description: "Figura coleccionable de Charmander, edición limitada",
        product_sku: "PKM001003",
        product_price: 5799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 5,
        img_front: "/img/pokemon/charmander-1.webp",
        img_back: "/img/pokemon/charmander-box.webp"
    },
    {
        product_id: 5,
        category_name: "Figuras colleccionables",
        licence_name: "Pokemon",
        product_name: "Pidgeotto",
        product_description: "Figura colleccionable de Pidgeotto, edicion limitada",
        product_sku: "PKM001004",
        product_price: 8799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 5,
        img_front: "/img/pokemon/pidgeotto-1.webp",
        img_back: "/img/pokemon/pidgeotto-box.webp",
    },
    {
        product_id: 6,
        category_name: "Figuras colleccionables",
        licence_name: "Star Wars",
        product_name: "BabyYoda Blueball",
        product_description: "Figura colleccionable de BabyYoda, edicion limitada",
        product_sku: "STW001002",
        product_price: 9799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 10,
        img_front: "/img/star-wars/baby-yoda-1.webp",
        img_back: "/img/star-wars/baby-yoda-box.webp",
    },
    {
    product_id: 7,
        category_name: "Figuras colleccionables",
        licence_name: "Pokemon",
        product_name: "Charmander Smiley",
        product_description: "Figura coleccionable de Charmander, edición limitada",
        product_sku: "PKM001005",
        product_price: 1799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 15,
        img_front: "/img/pokemon/charmander-1.webp",
        img_back: "/img/pokemon/charmander-box.webp",
    },
    {
        product_id: 8,
        category_name: "Figuras colleccionables",
        licence_name: "Pokemon",
        product_name: "Pidgeotto",
        product_description: "Figura colleccionable de Pidgeotto, edicion limitada",
        product_sku: "PKM001006",
        product_price: 1799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 5,
        img_front: "/img/pokemon/pidgeotto-1.webp",
        img_back: "/img/pokemon/pidgeotto-box.webp",
    },
    {
        product_id: 9,
        category_name: "Figuras colleccionables",
        licence_name: "Star Wars",
        product_name: "BabyYoda Blueball",
        product_description: "Figura colleccionable de BabyYoda, edicion limitada",
        product_sku: "STW001003",
        product_price: 1799.99,
        product_stock: "10 Uds",
        product_disccount: "10 %",
        product_dues: 5,
        img_front: "/img/star-wars/baby-yoda-1.webp",
        img_back: "/img/star-wars/baby-yoda-box.webp",
    }

]
module.exports = productosFalsos
